language: python
python:
  - 2.7
virtualenv:
  system_site_packages: true
before_install:
  - sudo apt-get install -qq libatlas3gf-base libatlas-dev
  - pip install --use-mirrors -qq numexpr
  - sudo apt-get update
  - sudo apt-get install -qq python-numpy
  - sudo apt-get install -qq python-scipy
  - sudo apt-get install -qq python-matplotlib
  - sudo apt-get install -qq libhdf5-serial-dev
  - sudo apt-get install -qq libfftw3-dev libfftw3-doc 
  - pip install --use-mirrors -qq nose
  - pip install --use-mirrors -qq cython
  - pip install --use-mirrors -qq tables
  - pip install --use-mirrors -qq pyyaml
  - pip install --use-mirrors -qq mdtraj
  - git clone --depth 5 https://github.com/hgomersall/pyFFTW.git; cd pyFFTW; python setup.py build_ext --inplace ; sudo python setup.py install ; cd ..
  - svn co https://svn.code.sf.net/p/fable/code/fabio/branches/v0.1.2 fabio; cd fabio; python setup.py install; cd ..
install:
  - python setup.py install
env:
  - TESTFOLDER=test
  - TESTFOLDER=test/xray
  - TESTFOLDER=test/xray/more
  - TESTFOLDER=test/scatter
script: nosetests -v "$TESTFOLDER"
